services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
      WHISPER_BASEURL: http://whisper:8080
      MEDIAMTX_WEBRTC_URL: http://mediamtx:8889
      MEDIAMTX_API_URL: http://mediamtx:8888
      MEDIAMTX_RTSP_HOST: mediamtx
      MEDIAMTX_RTSP_PORT: 8554
    volumes:
      - ./recordings:/recordings
    depends_on:
      - whisper
      - mediamtx

  whisper:
    image: ghcr.io/ggerganov/whisper.cpp:main-cuda
    entrypoint: ["./server"]
    command:
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8080"
      - "-m"
      - "/app/models/ggml-large-v3-turbo-q5_0.bin"
      - "--convert"
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./models:/app/models:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  mediamtx:
    image: bluenviron/mediamtx:latest
    restart: unless-stopped
    ports:
      - "8554:8554"
      - "9888:8888"
      - "8889:8889"
      - "8189:8189/udp"
    volumes:
      - ./recordings:/recordings
      - ./mediamtx.yml:/mediamtx.yml
    command: /mediamtx.yml
